# SPDX-License-Identifier: PMPL-1.0-or-later
name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.9', '1.10', '1.11']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: julia-actions/setup-julia@824fb972babf1837cf21c49159bf8a8130f26840 # v2
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.test()'
permissions: read-all
